// examples/web-vue/src/App.vue
<!--
  FortressAuth Vue Example
  Demonstrates authentication flows with comprehensive validation and accessibility.
-->
<script setup lang="ts">
import { useAuth, useUser } from '@fortressauth/vue-sdk';
import { computed, ref } from 'vue';
import {
  type FormErrors,
  hasErrors,
  sanitizeInput,
  validateEmail,
  validateResetPasswordForm,
  validateSignInForm,
  validateSignUpForm,
  validateVerifyEmailForm,
} from '../../shared/utils/validation';
import type { AlertType } from './components';
// biome-ignore lint/correctness/noUnusedImports: Components are used in Vue template section
import { Alert, Button, Input, Modal } from './components';

type AuthMode = 'signin' | 'signup' | 'verify' | 'reset';

interface FeedbackState {
  type: AlertType;
  message: string;
}

const { signUp, signIn, signOut, verifyEmail, requestPasswordReset, resetPassword } = useAuth();
// biome-ignore lint/correctness/noUnusedVariables: Variables are used in Vue template section
const { user, loading, error: authError } = useUser();

// Form state
const mode = ref<AuthMode>('signin');
const email = ref('');
const password = ref('');
const confirmPassword = ref('');
const token = ref('');

// UI state
const isSubmitting = ref(false);
const showResetModal = ref(false);
const feedback = ref<FeedbackState | null>(null);
const errors = ref<FormErrors>({});

// Show feedback message
function showFeedback(type: AlertType, message: string) {
  feedback.value = { type, message };
}

// Clear feedback
function clearFeedback() {
  feedback.value = null;
}

// Clear form state when switching modes
function handleModeChange(newMode: AuthMode) {
  mode.value = newMode;
  errors.value = {};
  clearFeedback();
}

// Reset form
function resetForm() {
  email.value = '';
  password.value = '';
  confirmPassword.value = '';
  token.value = '';
  errors.value = {};
}

// Get user-friendly error message
function getErrorMessage(error?: string): string {
  const errorMessages: Record<string, string> = {
    EMAIL_EXISTS: 'An account with this email already exists.',
    INVALID_CREDENTIALS: 'Invalid email or password. Please try again.',
    PASSWORD_TOO_WEAK: 'Password does not meet the requirements.',
    ACCOUNT_LOCKED: 'Your account has been temporarily locked. Please try again later.',
    EMAIL_NOT_VERIFIED: 'Please verify your email before signing in.',
    SESSION_INVALID: 'Your session is invalid. Please sign in again.',
    SESSION_EXPIRED: 'Your session has expired. Please sign in again.',
    EMAIL_VERIFICATION_INVALID: 'Invalid verification token.',
    EMAIL_VERIFICATION_EXPIRED: 'Verification token has expired. Please request a new one.',
    PASSWORD_RESET_INVALID: 'Invalid password reset token.',
    PASSWORD_RESET_EXPIRED: 'Password reset token has expired. Please request a new one.',
    RATE_LIMIT_EXCEEDED: 'Too many attempts. Please wait a moment and try again.',
  };

  return errorMessages[error || ''] || 'An error occurred. Please try again.';
}

// Get button text based on mode and state
// biome-ignore lint/correctness/noUnusedVariables: Variable is used in Vue template section
const buttonText = computed(() => {
  if (isSubmitting.value) {
    const loadingTexts: Record<AuthMode, string> = {
      signin: 'Signing in...',
      signup: 'Creating account...',
      verify: 'Verifying...',
      reset: 'Resetting password...',
    };
    return loadingTexts[mode.value];
  }

  const buttonTexts: Record<AuthMode, string> = {
    signin: 'Sign In',
    signup: 'Create Account',
    verify: 'Verify Email',
    reset: 'Reset Password',
  };
  return buttonTexts[mode.value];
});

// Handle form submission
// biome-ignore lint/correctness/noUnusedVariables: Function is used in Vue template section
async function handleSubmit() {
  clearFeedback();

  // Sanitize inputs
  const sanitizedEmail = sanitizeInput(email.value);
  const sanitizedToken = sanitizeInput(token.value);

  // Validate based on mode
  let validationErrors: FormErrors = {};

  switch (mode.value) {
    case 'signin':
      validationErrors = validateSignInForm(sanitizedEmail, password.value);
      break;
    case 'signup':
      validationErrors = validateSignUpForm(sanitizedEmail, password.value, confirmPassword.value);
      break;
    case 'verify':
      validationErrors = validateVerifyEmailForm(sanitizedToken);
      break;
    case 'reset':
      validationErrors = validateResetPasswordForm(
        sanitizedToken,
        password.value,
        confirmPassword.value,
      );
      break;
  }

  errors.value = validationErrors;

  if (hasErrors(validationErrors)) {
    return;
  }

  isSubmitting.value = true;

  try {
    switch (mode.value) {
      case 'signup': {
        const res = await signUp(sanitizedEmail, password.value);
        if (res.success) {
          showFeedback('success', 'Account created! Please check your email for verification.');
          resetForm();
        } else {
          showFeedback('error', getErrorMessage(res.error));
        }
        break;
      }

      case 'signin': {
        const res = await signIn(sanitizedEmail, password.value);
        if (res.success) {
          showFeedback('success', 'Welcome back!');
          resetForm();
        } else {
          showFeedback('error', getErrorMessage(res.error));
        }
        break;
      }

      case 'verify': {
        const res = await verifyEmail(sanitizedToken);
        if (res.success) {
          showFeedback('success', 'Email verified successfully! You can now sign in.');
          token.value = '';
          handleModeChange('signin');
        } else {
          showFeedback('error', getErrorMessage(res.error));
        }
        break;
      }

      case 'reset': {
        const res = await resetPassword(sanitizedToken, password.value);
        if (res.success) {
          showFeedback(
            'success',
            'Password reset successful! Please sign in with your new password.',
          );
          resetForm();
          handleModeChange('signin');
        } else {
          showFeedback('error', getErrorMessage(res.error));
        }
        break;
      }
    }
  } catch (_err) {
    showFeedback('error', 'An unexpected error occurred. Please try again.');
  } finally {
    isSubmitting.value = false;
  }
}

// Handle password reset request
// biome-ignore lint/correctness/noUnusedVariables: Function is used in Vue template section
async function handleRequestReset() {
  const sanitizedEmail = sanitizeInput(email.value);
  const emailValidation = validateEmail(sanitizedEmail);

  if (!emailValidation.isValid) {
    errors.value = { email: emailValidation.error };
    return;
  }

  isSubmitting.value = true;

  try {
    const res = await requestPasswordReset(sanitizedEmail);
    if (res.success) {
      showFeedback(
        'success',
        'If an account exists with this email, you will receive a password reset link.',
      );
      showResetModal.value = false;
      email.value = '';
    } else {
      showFeedback('error', getErrorMessage(res.error));
    }
  } catch (_err) {
    showFeedback('error', 'An unexpected error occurred. Please try again.');
  } finally {
    isSubmitting.value = false;
  }
}

// Handle sign out
// biome-ignore lint/correctness/noUnusedVariables: Function is used in Vue template section
async function handleSignOut() {
  isSubmitting.value = true;
  try {
    await signOut();
    showFeedback('info', 'You have been signed out.');
  } catch (_err) {
    showFeedback('error', 'Failed to sign out. Please try again.');
  } finally {
    isSubmitting.value = false;
  }
}

// Tab modes for navigation
// biome-ignore lint/correctness/noUnusedVariables: Variable is used in Vue template section
const tabModes: AuthMode[] = ['signin', 'signup', 'verify', 'reset'];

// biome-ignore lint/correctness/noUnusedVariables: Function is used in Vue template section
function getTabLabel(tabMode: AuthMode): string {
  const labels: Record<AuthMode, string> = {
    signin: 'Sign In',
    signup: 'Sign Up',
    verify: 'Verify',
    reset: 'Reset',
  };
  return labels[tabMode];
}
</script>

<template>
  <!-- Skip link for accessibility -->
  <a href="#main-content" class="skip-link">
    Skip to main content
  </a>

  <main id="main-content" class="container" role="main">
    <header class="header">
      <img
        src="/logo.svg"
        alt=""
        class="logo"
        aria-hidden="true"
      />
      <h1 class="title">FortressAuth</h1>
      <p class="subtitle">Secure Authentication Demo</p>
    </header>

    <!-- Loading state -->
    <div v-if="loading" class="loading" role="status" aria-live="polite">
      <span class="loading-spinner" aria-hidden="true" />
      <span>Loading session...</span>
    </div>

    <!-- Authenticated state -->
    <section v-else-if="user" class="authenticated" aria-labelledby="welcome-heading">
      <h2 id="welcome-heading" class="sr-only">Welcome</h2>
      
      <div class="user-info">
        <p class="welcome-text">
          Welcome, <span class="user-email">{{ user.email }}</span>
        </p>
        
        <div class="verification-status" role="status">
          <span
            :class="['status-badge', user.emailVerified ? 'status-verified' : 'status-unverified']"
            :aria-label="user.emailVerified ? 'Email verified' : 'Email not verified'"
          >
            {{ user.emailVerified ? '✓ Email Verified' : '⚠ Email Not Verified' }}
          </span>
        </div>
      </div>

      <Button
        variant="secondary"
        :loading="isSubmitting"
        loading-text="Signing out..."
        @click="handleSignOut"
      >
        Sign Out
      </Button>

      <Alert
        v-if="feedback"
        :type="feedback.type"
        :message="feedback.message"
        @dismiss="clearFeedback"
      />
    </section>

    <!-- Unauthenticated state -->
    <section v-else aria-labelledby="auth-heading">
      <h2 id="auth-heading" class="sr-only">Authentication</h2>

      <!-- Tab navigation -->
      <nav class="tabs" role="tablist" aria-label="Authentication options">
        <button
          v-for="tabMode in tabModes"
          :key="tabMode"
          type="button"
          role="tab"
          :class="['tab', { active: mode === tabMode }]"
          :aria-selected="mode === tabMode"
          :aria-controls="`${tabMode}-panel`"
          :id="`${tabMode}-tab`"
          @click="handleModeChange(tabMode)"
        >
          {{ getTabLabel(tabMode) }}
        </button>
      </nav>

      <!-- Form -->
      <form
        novalidate
        role="tabpanel"
        :id="`${mode}-panel`"
        :aria-labelledby="`${mode}-tab`"
        @submit.prevent="handleSubmit"
      >
        <!-- Email field - shown for signin and signup -->
        <Input
          v-if="mode === 'signin' || mode === 'signup'"
          v-model="email"
          type="email"
          label="Email"
          placeholder="your@email.com"
          :error="errors.email"
          required
          :autocomplete="mode === 'signin' ? 'email' : 'email'"
          :disabled="isSubmitting"
        />

        <!-- Token field - shown for verify and reset -->
        <Input
          v-if="mode === 'verify' || mode === 'reset'"
          v-model="token"
          type="text"
          :label="mode === 'verify' ? 'Verification Token' : 'Reset Token'"
          placeholder="selector:verifier"
          :error="errors.token"
          hint="Paste the token from your email"
          required
          autocomplete="off"
          :disabled="isSubmitting"
        />

        <!-- Password field - shown for signin, signup, and reset -->
        <Input
          v-if="mode === 'signin' || mode === 'signup' || mode === 'reset'"
          v-model="password"
          type="password"
          :label="mode === 'reset' ? 'New Password' : 'Password'"
          placeholder="••••••••"
          :error="errors.password"
          :hint="mode === 'signup' || mode === 'reset' ? 'Minimum 8 characters' : undefined"
          required
          :autocomplete="mode === 'signin' ? 'current-password' : 'new-password'"
          :disabled="isSubmitting"
        />

        <!-- Confirm password field - shown for signup and reset -->
        <Input
          v-if="mode === 'signup' || mode === 'reset'"
          v-model="confirmPassword"
          type="password"
          label="Confirm Password"
          placeholder="••••••••"
          :error="errors.confirmPassword"
          required
          autocomplete="new-password"
          :disabled="isSubmitting"
        />

        <Button
          type="submit"
          variant="primary"
          :loading="isSubmitting"
          :loading-text="buttonText"
        >
          {{ buttonText }}
        </Button>

        <!-- Forgot password link - shown for signin -->
        <div v-if="mode === 'signin'" class="forgot-password">
          <button
            type="button"
            class="link-button"
            @click="showResetModal = true"
          >
            Forgot your password?
          </button>
        </div>
      </form>

      <!-- Feedback messages -->
      <Alert
        v-if="authError"
        type="error"
        :message="getErrorMessage(authError)"
        @dismiss="clearFeedback"
      />

      <Alert
        v-if="feedback"
        :type="feedback.type"
        :message="feedback.message"
        @dismiss="clearFeedback"
      />
    </section>

    <!-- Password reset modal -->
    <Modal
      :is-open="showResetModal"
      title="Reset Password"
      description="Enter your email address and we'll send you a link to reset your password."
      @close="showResetModal = false"
    >
      <Input
        v-model="email"
        type="email"
        label="Email"
        placeholder="your@email.com"
        :error="errors.email"
        required
        autocomplete="email"
        :disabled="isSubmitting"
      />

      <div class="modal-actions">
        <Button
          type="button"
          variant="primary"
          :loading="isSubmitting"
          loading-text="Sending..."
          @click="handleRequestReset"
        >
          Send Reset Link
        </Button>
        <Button
          type="button"
          variant="secondary"
          :disabled="isSubmitting"
          @click="showResetModal = false"
        >
          Cancel
        </Button>
      </div>
    </Modal>
  </main>
</template>

// examples/mobile-expo/app/index.tsx
/**
 * FortressAuth Mobile Example - Main Screen
 *
 * This code works identically with both SDKs:
 *   - @fortressauth/expo-sdk (uses SecureStore - encrypted)
 *   - @fortressauth/react-native-sdk (uses AsyncStorage)
 *
 * Just change the import to switch between them!
 */

// For React Native CLI, change to: '@fortressauth/react-native-sdk'
import { useAuth, useUser } from '@fortressauth/expo-sdk';
import { StatusBar } from 'expo-status-bar';
import { useCallback, useState } from 'react';
import {
  ActivityIndicator,
  Alert as RNAlert,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import {
  type FormErrors,
  getErrorMessage,
  hasErrors,
  sanitizeInput,
  validateEmail,
  validateResetPasswordForm,
  validateSignInForm,
  validateSignUpForm,
  validateVerifyEmailForm,
} from '../../shared/utils/validation';
import { Alert, type AlertType, Button, Input, Logo, Modal } from '../components';
import { borderRadius, colors, spacing, typography } from '../styles/designTokens';

type AuthMode = 'signin' | 'signup' | 'verify' | 'reset';

interface FeedbackState {
  type: AlertType;
  message: string;
}

export default function HomeScreen() {
  const { signIn, signUp, signOut, verifyEmail, requestPasswordReset, resetPassword } = useAuth();
  const { user, loading, error: authError } = useUser();

  // Form state
  const [mode, setMode] = useState<AuthMode>('signin');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [token, setToken] = useState('');

  // UI state
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showResetModal, setShowResetModal] = useState(false);
  const [feedback, setFeedback] = useState<FeedbackState | null>(null);
  const [errors, setErrors] = useState<FormErrors>({});

  // Show feedback
  const showFeedback = useCallback((type: AlertType, message: string) => {
    setFeedback({ type, message });
  }, []);

  const clearFeedback = useCallback(() => {
    setFeedback(null);
  }, []);

  // Clear form state when switching modes
  const handleModeChange = useCallback(
    (newMode: AuthMode) => {
      setMode(newMode);
      setErrors({});
      clearFeedback();
    },
    [clearFeedback],
  );

  // Reset form
  const resetForm = useCallback(() => {
    setEmail('');
    setPassword('');
    setConfirmPassword('');
    setToken('');
    setErrors({});
  }, []);

  // Handle form submission
  const handleSubmit = async () => {
    clearFeedback();

    // Sanitize inputs
    const sanitizedEmail = sanitizeInput(email);
    const sanitizedToken = sanitizeInput(token);

    // Validate based on mode
    let validationErrors: FormErrors = {};

    switch (mode) {
      case 'signin':
        validationErrors = validateSignInForm(sanitizedEmail, password);
        break;
      case 'signup':
        validationErrors = validateSignUpForm(sanitizedEmail, password, confirmPassword);
        break;
      case 'verify':
        validationErrors = validateVerifyEmailForm(sanitizedToken);
        break;
      case 'reset':
        validationErrors = validateResetPasswordForm(sanitizedToken, password, confirmPassword);
        break;
    }

    setErrors(validationErrors);

    if (hasErrors(validationErrors)) {
      return;
    }

    setIsSubmitting(true);

    try {
      switch (mode) {
        case 'signup': {
          const res = await signUp(sanitizedEmail, password);
          if (res.success) {
            showFeedback('success', 'Account created! Please check your email for verification.');
            resetForm();
          } else {
            showFeedback('error', getErrorMessage(res.error));
          }
          break;
        }

        case 'signin': {
          const res = await signIn(sanitizedEmail, password);
          if (res.success) {
            showFeedback('success', 'Welcome back!');
            resetForm();
          } else {
            showFeedback('error', getErrorMessage(res.error));
          }
          break;
        }

        case 'verify': {
          const res = await verifyEmail(sanitizedToken);
          if (res.success) {
            showFeedback('success', 'Email verified successfully! You can now sign in.');
            setToken('');
            handleModeChange('signin');
          } else {
            showFeedback('error', getErrorMessage(res.error));
          }
          break;
        }

        case 'reset': {
          const res = await resetPassword(sanitizedToken, password);
          if (res.success) {
            showFeedback(
              'success',
              'Password reset successful! Please sign in with your new password.',
            );
            resetForm();
            handleModeChange('signin');
          } else {
            showFeedback('error', getErrorMessage(res.error));
          }
          break;
        }
      }
    } catch (_err) {
      showFeedback('error', 'An unexpected error occurred. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  // Handle password reset request
  const handleRequestReset = async () => {
    const sanitizedEmail = sanitizeInput(email);
    const emailValidation = validateEmail(sanitizedEmail);

    if (!emailValidation.isValid) {
      setErrors({ email: emailValidation.error });
      return;
    }

    setIsSubmitting(true);

    try {
      const res = await requestPasswordReset(sanitizedEmail);
      if (res.success) {
        RNAlert.alert(
          'Success',
          'If an account exists with this email, you will receive a password reset link.',
        );
        setShowResetModal(false);
        setEmail('');
      } else {
        showFeedback('error', getErrorMessage(res.error));
      }
    } catch (_err) {
      showFeedback('error', 'An unexpected error occurred. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  // Handle sign out
  const handleSignOut = async () => {
    setIsSubmitting(true);
    try {
      await signOut();
      showFeedback('info', 'You have been signed out.');
    } catch (_err) {
      showFeedback('error', 'Failed to sign out. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  // Get button text based on mode and state
  const getButtonText = (): string => {
    if (isSubmitting) {
      const loadingTexts: Record<AuthMode, string> = {
        signin: 'Signing in...',
        signup: 'Creating account...',
        verify: 'Verifying...',
        reset: 'Resetting password...',
      };
      return loadingTexts[mode];
    }

    const buttonTexts: Record<AuthMode, string> = {
      signin: 'Sign In',
      signup: 'Create Account',
      verify: 'Verify Email',
      reset: 'Reset Password',
    };
    return buttonTexts[mode];
  };

  if (loading) {
    return (
      <View style={styles.container}>
        <StatusBar style="light" />
        <View style={styles.loading}>
          <ActivityIndicator size="large" color={colors.primary[400]} />
          <Text style={styles.loadingText}>Loading session...</Text>
        </View>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <StatusBar style="light" />
      <ScrollView contentContainerStyle={styles.scrollContent} keyboardShouldPersistTaps="handled">
        <View style={styles.card}>
          {/* Header */}
          <View style={styles.header}>
            <Logo width={64} height={64} />
            <Text style={styles.title}>FortressAuth</Text>
            <Text style={styles.subtitle}>Secure Authentication Demo</Text>
          </View>

          {user ? (
            // Authenticated state
            <View style={styles.authenticated}>
              <View style={styles.userInfo}>
                <Text style={styles.welcomeText}>
                  Welcome, <Text style={styles.userEmail}>{user.email}</Text>
                </Text>

                <View
                  style={[
                    styles.statusBadge,
                    user.emailVerified ? styles.statusVerified : styles.statusUnverified,
                  ]}
                >
                  <Text
                    style={[
                      styles.statusText,
                      { color: user.emailVerified ? colors.success : colors.warning },
                    ]}
                  >
                    {user.emailVerified ? '✓ Email Verified' : '⚠ Email Not Verified'}
                  </Text>
                </View>
              </View>

              <Button
                variant="secondary"
                onPress={handleSignOut}
                loading={isSubmitting}
                loadingText="Signing out..."
              >
                Sign Out
              </Button>

              {feedback && (
                <Alert type={feedback.type} message={feedback.message} onDismiss={clearFeedback} />
              )}
            </View>
          ) : (
            // Unauthenticated state
            <>
              {/* Tab navigation */}
              <View style={styles.tabs} accessibilityRole="tablist">
                {(['signin', 'signup', 'verify', 'reset'] as AuthMode[]).map((tabMode) => (
                  <TouchableOpacity
                    key={tabMode}
                    style={[styles.tab, mode === tabMode && styles.tabActive]}
                    onPress={() => handleModeChange(tabMode)}
                    accessibilityRole="tab"
                    accessibilityState={{ selected: mode === tabMode }}
                  >
                    <Text style={[styles.tabText, mode === tabMode && styles.tabTextActive]}>
                      {tabMode === 'signin' && 'Sign In'}
                      {tabMode === 'signup' && 'Sign Up'}
                      {tabMode === 'verify' && 'Verify'}
                      {tabMode === 'reset' && 'Reset'}
                    </Text>
                  </TouchableOpacity>
                ))}
              </View>

              {/* Form */}
              <View style={styles.form}>
                {/* Email field - shown for signin and signup */}
                {(mode === 'signin' || mode === 'signup') && (
                  <Input
                    label="Email"
                    value={email}
                    onChangeText={setEmail}
                    placeholder="your@email.com"
                    error={errors.email}
                    required
                    autoCapitalize="none"
                    autoComplete="email"
                    keyboardType="email-address"
                    editable={!isSubmitting}
                  />
                )}

                {/* Token field - shown for verify and reset */}
                {(mode === 'verify' || mode === 'reset') && (
                  <Input
                    label={mode === 'verify' ? 'Verification Token' : 'Reset Token'}
                    value={token}
                    onChangeText={setToken}
                    placeholder="selector:verifier"
                    error={errors.token}
                    hint="Paste the token from your email"
                    required
                    autoCapitalize="none"
                    autoComplete="off"
                    editable={!isSubmitting}
                  />
                )}

                {/* Password field - shown for signin, signup, and reset */}
                {(mode === 'signin' || mode === 'signup' || mode === 'reset') && (
                  <Input
                    label={mode === 'reset' ? 'New Password' : 'Password'}
                    value={password}
                    onChangeText={setPassword}
                    placeholder="••••••••"
                    error={errors.password}
                    hint={
                      mode === 'signup' || mode === 'reset' ? 'Minimum 8 characters' : undefined
                    }
                    required
                    secureTextEntry
                    autoComplete={mode === 'signin' ? 'current-password' : 'new-password'}
                    editable={!isSubmitting}
                  />
                )}

                {/* Confirm password field - shown for signup and reset */}
                {(mode === 'signup' || mode === 'reset') && (
                  <Input
                    label="Confirm Password"
                    value={confirmPassword}
                    onChangeText={setConfirmPassword}
                    placeholder="••••••••"
                    error={errors.confirmPassword}
                    required
                    secureTextEntry
                    autoComplete="new-password"
                    editable={!isSubmitting}
                  />
                )}

                <Button
                  variant="primary"
                  onPress={handleSubmit}
                  loading={isSubmitting}
                  loadingText={getButtonText()}
                >
                  {getButtonText()}
                </Button>

                {/* Forgot password link - shown for signin */}
                {mode === 'signin' && (
                  <TouchableOpacity
                    style={styles.forgotPassword}
                    onPress={() => setShowResetModal(true)}
                  >
                    <Text style={styles.forgotPasswordText}>Forgot your password?</Text>
                  </TouchableOpacity>
                )}
              </View>

              {/* Feedback messages */}
              {authError && (
                <Alert
                  type="error"
                  message={getErrorMessage(authError)}
                  onDismiss={clearFeedback}
                />
              )}

              {feedback && (
                <Alert type={feedback.type} message={feedback.message} onDismiss={clearFeedback} />
              )}
            </>
          )}
        </View>

        {/* Password reset modal */}
        <Modal
          isOpen={showResetModal}
          onClose={() => setShowResetModal(false)}
          title="Reset Password"
          description="Enter your email address and we'll send you a link to reset your password."
        >
          <Input
            label="Email"
            value={email}
            onChangeText={setEmail}
            placeholder="your@email.com"
            error={errors.email}
            required
            autoCapitalize="none"
            autoComplete="email"
            keyboardType="email-address"
            editable={!isSubmitting}
          />

          <View style={styles.modalActions}>
            <Button
              variant="primary"
              onPress={handleRequestReset}
              loading={isSubmitting}
              loadingText="Sending..."
            >
              Send Reset Link
            </Button>
            <Button
              variant="secondary"
              onPress={() => setShowResetModal(false)}
              disabled={isSubmitting}
            >
              Cancel
            </Button>
          </View>
        </Modal>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg.primary,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: spacing[4],
  },
  card: {
    backgroundColor: colors.bg.tertiary,
    borderRadius: borderRadius.xl,
    borderWidth: 1,
    borderColor: colors.border.secondary,
    padding: spacing[10],
    maxWidth: 480,
    width: '100%',
    alignSelf: 'center',
  },
  header: {
    alignItems: 'center',
    marginBottom: spacing[8],
  },
  title: {
    fontSize: typography.fontSize['2xl'],
    fontWeight: typography.fontWeight.semibold,
    color: colors.text.primary,
    marginTop: spacing[4],
  },
  subtitle: {
    fontSize: typography.fontSize.sm,
    color: colors.text.secondary,
    marginTop: spacing[2],
  },
  loading: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing[4],
  },
  loadingText: {
    color: colors.text.secondary,
    fontSize: typography.fontSize.base,
  },
  tabs: {
    flexDirection: 'row',
    marginBottom: spacing[6],
    borderBottomWidth: 1,
    borderBottomColor: colors.border.secondary,
  },
  tab: {
    flex: 1,
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[4],
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
    alignItems: 'center',
  },
  tabActive: {
    borderBottomColor: colors.text.accent,
  },
  tabText: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    color: colors.text.secondary,
  },
  tabTextActive: {
    color: colors.text.accent,
  },
  form: {
    width: '100%',
  },
  forgotPassword: {
    marginTop: spacing[4],
    alignItems: 'center',
    padding: spacing[1],
  },
  forgotPasswordText: {
    fontSize: typography.fontSize.sm,
    color: colors.text.secondary,
  },
  authenticated: {
    alignItems: 'center',
  },
  userInfo: {
    alignItems: 'center',
    marginBottom: spacing[6],
  },
  welcomeText: {
    fontSize: typography.fontSize.lg,
    color: colors.text.primary,
    marginBottom: spacing[4],
  },
  userEmail: {
    color: colors.text.accent,
    fontWeight: typography.fontWeight.medium,
  },
  statusBadge: {
    paddingVertical: spacing[2],
    paddingHorizontal: spacing[4],
    borderRadius: borderRadius.full,
    borderWidth: 1,
  },
  statusVerified: {
    backgroundColor: colors.successBg,
    borderColor: colors.success,
  },
  statusUnverified: {
    backgroundColor: colors.warningBg,
    borderColor: colors.warning,
  },
  statusText: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
  },
  modalActions: {
    marginTop: spacing[4],
    gap: spacing[3],
  },
});
