// examples/web-react/src/components/Input.tsx
/**
 * FortressAuth - Input Component
 * Accessible form input with validation states and error messages.
 */

import type React from 'react';
import { useId } from 'react';
import './Input.css';

export interface InputProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'id'> {
  label: string;
  error?: string | undefined;
  hint?: string | undefined;
}

export const Input: React.FC<InputProps> = ({
  label,
  error,
  hint,
  className = '',
  required,
  ...props
}) => {
  const id = useId();
  const errorId = `${id}-error`;
  const hintId = `${id}-hint`;

  const hasError = Boolean(error);
  const describedBy =
    [hasError ? errorId : null, hint ? hintId : null].filter(Boolean).join(' ') || undefined;

  return (
    <div className={`form-group ${hasError ? 'has-error' : ''} ${className}`}>
      <label htmlFor={id} className="form-label">
        {label}
        {required && (
          <span className="form-required" aria-hidden="true">
            {' '}
            *
          </span>
        )}
      </label>

      <input
        id={id}
        className={`form-input ${hasError ? 'input-error' : ''}`}
        aria-invalid={hasError}
        aria-describedby={describedBy}
        aria-required={required}
        required={required}
        {...props}
      />

      {hint && !hasError && (
        <p id={hintId} className="form-hint">
          {hint}
        </p>
      )}

      {hasError && (
        <p id={errorId} className="form-error" role="alert">
          {error}
        </p>
      )}
    </div>
  );
};

export default Input;

// examples/web-vue/src/components/Input.vue
<!--
  FortressAuth - Input Component (Vue)
  Accessible form input with validation states and error messages.
-->
<script setup lang="ts">
import { computed, useId } from 'vue';
import type { InputProps } from './types';

const props = withDefaults(defineProps<InputProps>(), {
  type: 'text',
  placeholder: '',
  required: false,
  disabled: false,
  autoComplete: 'off',
});

const emit = defineEmits<{
  'update:modelValue': [value: string];
}>();

const id = useId();
const errorId = computed(() => `${id}-error`);
const hintId = computed(() => `${id}-hint`);

const hasError = computed(() => Boolean(props.error));

// biome-ignore lint/correctness/noUnusedVariables: Variable is used in Vue template section
const describedBy = computed(() => {
  const ids: string[] = [];
  if (hasError.value) ids.push(errorId.value);
  else if (props.hint) ids.push(hintId.value);
  return ids.length > 0 ? ids.join(' ') : undefined;
});

// biome-ignore lint/correctness/noUnusedVariables: Function is used in Vue template section
function handleInput(event: Event) {
  const target = event.target as HTMLInputElement;
  emit('update:modelValue', target.value);
}
</script>

<template>
  <div :class="['form-group', { 'has-error': hasError }]">
    <label :for="id" class="form-label">
      {{ label }}
      <span v-if="required" class="form-required" aria-hidden="true"> *</span>
    </label>
    
    <input
      :id="id"
      :type="type"
      :value="modelValue"
      :class="['form-input', { 'input-error': hasError }]"
      :placeholder="placeholder"
      :required="required"
      :disabled="disabled"
      :autocomplete="autoComplete"
      :aria-invalid="hasError"
      :aria-describedby="describedBy"
      :aria-required="required"
      @input="handleInput"
    />
    
    <p v-if="hint && !hasError" :id="hintId" class="form-hint">
      {{ hint }}
    </p>
    
    <p v-if="hasError" :id="errorId" class="form-error" role="alert">
      {{ error }}
    </p>
  </div>
</template>
