// examples/web-vue/src/components/Button.vue
<!--
  FortressAuth - Button Component (Vue)
  Accessible button with loading states and variants.
-->
<script setup lang="ts">
import { computed } from 'vue';
import type { ButtonProps } from './types';

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'primary',
  size: 'md',
  loading: false,
  loadingText: 'Loading...',
  fullWidth: true,
  disabled: false,
  type: 'button',
});

// biome-ignore lint/correctness/noUnusedVariables: Variable is used in Vue template section
const isDisabled = computed(() => props.disabled || props.loading);
</script>

<template>
  <button
    :type="type"
    :class="[
      'btn',
      `btn-${variant}`,
      `btn-${size}`,
      { 'btn-full': fullWidth }
    ]"
    :disabled="isDisabled"
    :aria-busy="loading"
    :aria-disabled="isDisabled"
  >
    <template v-if="loading">
      <span class="btn-spinner" aria-hidden="true" />
      <span>{{ loadingText }}</span>
    </template>
    <template v-else>
      <slot />
    </template>
  </button>
</template>

// examples/web-react/src/components/Button.tsx
/**
 * FortressAuth - Button Component
 * Accessible button with loading states and variants.
 */

import type React from 'react';
import './Button.css';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost';
export type ButtonSize = 'sm' | 'md' | 'lg';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  loading?: boolean;
  loadingText?: string;
  fullWidth?: boolean;
  children: React.ReactNode;
}

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'md',
  loading = false,
  loadingText,
  fullWidth = true,
  children,
  disabled,
  className = '',
  ...props
}) => {
  const isDisabled = disabled || loading;

  return (
    <button
      className={`btn btn-${variant} btn-${size} ${fullWidth ? 'btn-full' : ''} ${className}`}
      disabled={isDisabled}
      aria-busy={loading}
      aria-disabled={isDisabled}
      {...props}
    >
      {loading ? (
        <>
          <span className="btn-spinner" aria-hidden="true" />
          <span>{loadingText || 'Loading...'}</span>
        </>
      ) : (
        children
      )}
    </button>
  );
};

export default Button;
