// examples/web-vue/src/components/Modal.vue
<!--
  FortressAuth - Modal Component (Vue)
  Accessible modal dialog with focus management.
-->
<script setup lang="ts">
import { nextTick, onUnmounted, ref, watch } from 'vue';
import type { ModalProps } from './types';

const props = defineProps<ModalProps>();

const emit = defineEmits<{
  close: [];
}>();

const modalRef = ref<HTMLDivElement | null>(null);
let previousActiveElement: HTMLElement | null = null;

// Handle escape key
function handleEscape(e: KeyboardEvent) {
  if (e.key === 'Escape') {
    emit('close');
  }
}

// Handle click outside modal
// biome-ignore lint/correctness/noUnusedVariables: Function is used in Vue template section
function handleOverlayClick(e: MouseEvent) {
  if (e.target === e.currentTarget) {
    emit('close');
  }
}

// Trap focus within modal
// biome-ignore lint/correctness/noUnusedVariables: Function is used in Vue template section
function handleKeyDown(e: KeyboardEvent) {
  if (e.key !== 'Tab') return;

  const focusableElements = modalRef.value?.querySelectorAll<HTMLElement>(
    'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
  );

  if (!focusableElements || focusableElements.length === 0) return;

  const firstElement = focusableElements[0];
  const lastElement = focusableElements[focusableElements.length - 1];

  if (!firstElement || !lastElement) return;

  if (e.shiftKey && document.activeElement === firstElement) {
    e.preventDefault();
    lastElement.focus();
  } else if (!e.shiftKey && document.activeElement === lastElement) {
    e.preventDefault();
    firstElement.focus();
  }
}

watch(
  () => props.isOpen,
  async (isOpen) => {
    if (isOpen) {
      // Store the currently focused element
      previousActiveElement = document.activeElement as HTMLElement;

      // Prevent body scroll
      document.body.style.overflow = 'hidden';

      // Add escape key listener
      document.addEventListener('keydown', handleEscape);

      // Focus the modal after it's rendered
      await nextTick();
      modalRef.value?.focus();
    } else {
      // Remove escape key listener
      document.removeEventListener('keydown', handleEscape);

      // Restore body scroll
      document.body.style.overflow = '';

      // Restore focus to the previously focused element
      previousActiveElement?.focus();
    }
  },
);

onUnmounted(() => {
  document.removeEventListener('keydown', handleEscape);
  document.body.style.overflow = '';
});
</script>

<template>
  <Teleport to="body">
    <div
      v-if="isOpen"
      class="modal-overlay"
      role="presentation"
      @click="handleOverlayClick"
    >
      <div
        ref="modalRef"
        class="modal"
        role="dialog"
        aria-modal="true"
        aria-labelledby="modal-title"
        :aria-describedby="description ? 'modal-description' : undefined"
        tabindex="-1"
        @keydown="handleKeyDown"
      >
        <div class="modal-header">
          <h2 id="modal-title" class="modal-title">
            {{ title }}
          </h2>
          <button
            type="button"
            class="modal-close"
            aria-label="Close dialog"
            @click="emit('close')"
          >
            ×
          </button>
        </div>
        
        <p v-if="description" id="modal-description" class="modal-description">
          {{ description }}
        </p>
        
        <div class="modal-content">
          <slot />
        </div>
      </div>
    </div>
  </Teleport>
</template>

// examples/web-react/src/components/Modal.tsx
/**
 * FortressAuth - Modal Component
 * Accessible modal dialog with focus management.
 */

import type React from 'react';
import { useEffect, useRef } from 'react';
import './Modal.css';

export interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  description?: string;
  children: React.ReactNode;
}

export const Modal: React.FC<ModalProps> = ({ isOpen, onClose, title, description, children }) => {
  const modalRef = useRef<HTMLDivElement>(null);
  const previousActiveElement = useRef<HTMLElement | null>(null);

  useEffect(() => {
    if (isOpen) {
      // Store the currently focused element
      previousActiveElement.current = document.activeElement as HTMLElement;

      // Focus the modal
      modalRef.current?.focus();

      // Prevent body scroll
      document.body.style.overflow = 'hidden';

      // Handle escape key
      const handleEscape = (e: KeyboardEvent) => {
        if (e.key === 'Escape') {
          onClose();
        }
      };

      document.addEventListener('keydown', handleEscape);

      return () => {
        document.removeEventListener('keydown', handleEscape);
        document.body.style.overflow = '';

        // Restore focus to the previously focused element
        previousActiveElement.current?.focus();
      };
    }
    return undefined;
  }, [isOpen, onClose]);

  // Handle click outside modal
  const handleOverlayClick = (e: React.MouseEvent) => {
    if (e.target === e.currentTarget) {
      onClose();
    }
  };

  // Trap focus within modal
  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key !== 'Tab') return;

    const focusableElements = modalRef.current?.querySelectorAll<HTMLElement>(
      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
    );

    if (!focusableElements || focusableElements.length === 0) return;

    const firstElement = focusableElements[0];
    const lastElement = focusableElements[focusableElements.length - 1];

    if (!firstElement || !lastElement) return;

    if (e.shiftKey && document.activeElement === firstElement) {
      e.preventDefault();
      lastElement.focus();
    } else if (!e.shiftKey && document.activeElement === lastElement) {
      e.preventDefault();
      firstElement.focus();
    }
  };

  if (!isOpen) return null;

  return (
    // biome-ignore lint/a11y/noStaticElementInteractions: Overlay click-to-close is a common modal pattern, keyboard handling is managed by the modal's onKeyDown handler
    <div className="modal-overlay" onClick={handleOverlayClick} role="presentation">
      <div
        ref={modalRef}
        className="modal"
        role="dialog"
        aria-modal="true"
        aria-labelledby="modal-title"
        aria-describedby={description ? 'modal-description' : undefined}
        tabIndex={-1}
        onKeyDown={handleKeyDown}
      >
        <div className="modal-header">
          <h2 id="modal-title" className="modal-title">
            {title}
          </h2>
          <button type="button" className="modal-close" onClick={onClose} aria-label="Close dialog">
            ×
          </button>
        </div>

        {description && (
          <p id="modal-description" className="modal-description">
            {description}
          </p>
        )}

        <div className="modal-content">{children}</div>
      </div>
    </div>
  );
};

export default Modal;
